version: 2.1
orbs:
  slack: circleci/slack@3.3.0
jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.38.0
      - run: make golangci-lint
      - slack/notify-on-failure:
          only_for_branches: main
          
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - Tilt Slack Context
